// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWN7KVXP5zej45BLCPKuOC_52Xr56Q6WA',
    appId: '1:215102121509:web:b3aef327e1ef82bd60c1cc',
    messagingSenderId: '215102121509',
    projectId: 'todo-flutter-challenge',
    authDomain: 'todo-flutter-challenge.firebaseapp.com',
    storageBucket: 'todo-flutter-challenge.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLbTqal31GCpzWimBH1ii-rRBX8P60dvQ',
    appId: '1:215102121509:android:cd54cdd26074ccdb60c1cc',
    messagingSenderId: '215102121509',
    projectId: 'todo-flutter-challenge',
    storageBucket: 'todo-flutter-challenge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNIkxcoSuLnLGvJFexrliewuMlT1K9ruo',
    appId: '1:215102121509:ios:f9a4c08f774f961160c1cc',
    messagingSenderId: '215102121509',
    projectId: 'todo-flutter-challenge',
    storageBucket: 'todo-flutter-challenge.appspot.com',
    iosClientId: '215102121509-8qppmqlfnnf5o1ko5smdm3dgebtpfa1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
